import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PlaylistManager,nextOnEnded,playbackModes} from '../src/audio/PlaylistManager.js';
class Audio extends EventTarget{
 constructor(){super();this.generation=0;this.media={ended:false,paused:true};this.plays=0;}
 load(){this.generation++;this.media.ended=false;this.media.paused=true;}
 async play(){this.media.paused=false;this.plays++;}
 pause(){this.media.paused=true;}
 end(){this.media.ended=true;this.media.paused=true;this.dispatchEvent(new Event('ended'));}
}
const setup=(songs=[{id:'a'},{id:'b'},{id:'c'}])=>{const audio=new Audio(),activated=[],events=[];const manager=new PlaylistManager({audio,songs,activate:i=>{activated.push(i);audio.load();events.push('activate');},beforeLeave:r=>events.push(r)});return {manager,audio,activated,events,songs};};
test('All four end policies, including empty and one-item lists',()=>{for(const mode of Object.keys(playbackModes)){assert.equal(nextOnEnded(mode,0,0),null);assert.equal(nextOnEnded(mode,-1,3),null);}assert.deepEqual([0,1,2].map(i=>nextOnEnded('single',i,3)),[null,null,null]);assert.deepEqual([0,1,2].map(i=>nextOnEnded('loopOne',i,3)),[0,1,2]);assert.deepEqual([0,1,2].map(i=>nextOnEnded('sequential',i,3)),[1,2,null]);assert.deepEqual([0,1,2].map(i=>nextOnEnded('loopPlaylist',i,3)),[1,2,0]);assert.equal(nextOnEnded('sequential',0,1),null);assert.equal(nextOnEnded('loopPlaylist',0,1),0);});
test('Sequential auto-advances and stops at end; terminal event runs before activation',async()=>{const {manager,audio,activated,events}=setup();manager.setMode('sequential');await manager.select(0,{autoplay:true});audio.end();await Promise.resolve();assert.equal(manager.index,1);assert.deepEqual(events.slice(-3),['ended','continuation','activate']);audio.end();await Promise.resolve();audio.end();assert.deepEqual(activated,[0,1,2]);assert.equal(manager.wantsPlayback,false);assert.equal(audio.plays,3);});
test('Loop One reloads same track; duplicate ended delivery cannot skip tracks',async()=>{const {manager,audio,activated}=setup();manager.setMode('loopOne');await manager.select(1,{autoplay:true});audio.end();audio.dispatchEvent(new Event('ended'));assert.deepEqual(activated,[1,1]);assert.equal(manager.index,1);manager.setMode('loopPlaylist');await manager.select(2,{autoplay:true});audio.end();assert.equal(manager.index,0);});
test('Navigation preserves paused/playing intent, wraps explicitly, uses IDs after list mutation',async()=>{const {manager,audio,songs}=setup();await manager.select(0);await manager.move(-1);assert.equal(manager.index,2);assert.equal(audio.media.paused,true);await manager.play();songs.splice(0,1);assert.equal(manager.index,1);await manager.move(1);assert.equal(manager.currentId,'b');assert.equal(audio.media.paused,false);manager.pause();await manager.move(1);assert.equal(audio.media.paused,true);manager.setMode('garbage');assert.equal(manager.mode,'single');});
test('Stale play rejection cannot stop newer selection; disposal unhooks ended',async()=>{const {manager,audio}=setup();let rejectOld;audio.play=()=>new Promise((_,reject)=>rejectOld=reject);const old=manager.select(0,{autoplay:true});await manager.select(1,{autoplay:false});rejectOld(Error('old aborted'));await old;assert.equal(manager.currentId,'b');assert.equal(manager.wantsPlayback,false);manager.dispose();audio.end();assert.equal(manager.currentId,'b');});
