import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const results={};
const waitId=async id=>page.waitForFunction(id=>window.__LIVE__.playlist.currentId===id&&window.__LIVE__.audio.running,id);
const end=async()=>{const count=await page.evaluate(()=>window.testEnds);await page.evaluate(()=>{const a=window.__LIVE__;a.audio.seek(a.audio.media.duration-.08);});await page.waitForFunction(count=>window.testEnds>count,count);};
try{
 await page.goto('http://localhost:5173/');await page.waitForFunction(()=>window.__LIVE__?.characters.characters.length===5,{},{timeout:90000});await page.waitForFunction(()=>!!window.__LIVE__.songLibrary.db);
 await page.screenshot({path:'reports/playlist-desktop.png'});
 await page.evaluate(()=>{const a=window.__LIVE__,fixtures=[];for(let k=0;k<3;k++){const rate=8000,n=rate*4,b=new ArrayBuffer(44+n*2),v=new DataView(b);const str=(p,s)=>[...s].forEach((c,i)=>v.setUint8(p+i,c.charCodeAt(0)));str(0,'RIFF');v.setUint32(4,36+n*2,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,n*2,true);for(let i=0;i<n;i++)v.setInt16(44+i*2,Math.sin(i*2*Math.PI*220/rate)*500,true);fixtures.push({id:'fixture'+k,title:'播放列表测试 '+(k+1),bpm:[90,160,210][k],offset:[.05,.12,.21][k],file:URL.createObjectURL(new Blob([b],{type:'audio/wav'}))});}
 a.songLibrary.songs.splice(0,a.songLibrary.songs.length,...fixtures);a.ui.refreshSongs(fixtures);window.testEnds=0;window.testChanges=[];window.baseline={scene:a.scene,camera:a.camera,renderer:a.renderer,roots:a.characters.characters.map(c=>c.root),loaded:a.assets.loaded};a.audio.media.addEventListener('ended',()=>window.testEnds++);a.addEventListener('songchange',e=>testChanges.push({...e.detail,song:e.detail.song.id,energy:a.audio.bands.energy,running:a.audio.running}));a.song(0);});
 await page.locator('#playback-mode').selectOption('single');await page.locator('#start').click();await waitId('fixture0');await end();results.single=await page.evaluate(()=>({id:window.__LIVE__.playlist.currentId,paused:window.__LIVE__.audio.media.paused,wants:window.__LIVE__.playlist.wantsPlayback}));
 await page.locator('#playback-mode').selectOption('loopOne');await page.locator('#play').click();await waitId('fixture0');const gen=await page.evaluate(()=>window.__LIVE__.audio.generation);await end();await page.waitForFunction(g=>window.__LIVE__.audio.generation>g&&window.__LIVE__.audio.running,gen);results.loopOne=await page.evaluate(()=>({id:window.__LIVE__.playlist.currentId,time:window.__LIVE__.audio.time}));
 await page.locator('#playback-mode').selectOption('sequential');await end();await waitId('fixture1');await end();await waitId('fixture2');await end();results.sequential=await page.evaluate(()=>({id:window.__LIVE__.playlist.currentId,paused:window.__LIVE__.audio.media.paused,wants:window.__LIVE__.playlist.wantsPlayback}));
 await page.locator('#playback-mode').selectOption('loopPlaylist');await page.locator('#play').click();await waitId('fixture2');await end();await waitId('fixture0');results.loopPlaylist=true;
 await page.locator('#next').click();await waitId('fixture1');await page.locator('#play').click();await page.locator('#previous').click();results.pausedNavigation=await page.evaluate(()=>({id:window.__LIVE__.playlist.currentId,paused:window.__LIVE__.audio.media.paused}));
 results.sync=await page.evaluate(()=>({changes:window.testChanges,nativeEnds:window.testEnds,sameScene:baseline.scene===__LIVE__.scene,sameCamera:baseline.camera===__LIVE__.camera,sameRenderer:baseline.renderer===__LIVE__.renderer,sameModels:baseline.roots.every((root,i)=>__LIVE__.characters.characters[i].root===root),extraLoads:__LIVE__.assets.loaded-baseline.loaded}));
 // User pause while AudioContext.resume is pending must win.
 results.cancelledResume=await page.evaluate(async()=>{const a=window.__LIVE__,context=a.audio.context,original=context.resume.bind(context);let release;context.resume=()=>new Promise(r=>release=r);const pending=a.playlist.play();a.playlist.pause();release();await pending;context.resume=original;return {paused:a.audio.media.paused,wants:a.playlist.wantsPlayback};});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'reports/playlist-mobile.png'});results.mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);await page.reload();await page.waitForFunction(()=>window.__LIVE__?.playlist);results.modePersisted=await page.locator('#playback-mode').inputValue();results.errors=errors;
 await fs.writeFile('reports/playlist-qa.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
 const validChanges=results.sync.changes.every(c=>c.energy===0&&!c.running&&c.bpm===[90,160,210][Number(c.song.slice(-1))]&&c.offset===[.05,.12,.21][Number(c.song.slice(-1))]);
 if(errors.length||!results.single.paused||results.single.wants||results.loopOne.id!=='fixture0'||results.sequential.id!=='fixture2'||results.sequential.wants||!results.pausedNavigation.paused||!results.sync.sameScene||!results.sync.sameCamera||!results.sync.sameRenderer||!results.sync.sameModels||results.sync.extraLoads||!validChanges||!results.cancelledResume.paused||results.cancelledResume.wants||results.mobileOverflow||results.modePersisted!=='loopPlaylist')process.exitCode=1;
}finally{await browser.close();}
